# Site Info
title:              "Max Phillips"
description:        "Personal blog of Max Phillips (BlueyBloke)."
author_name:        "Maxwell Phillips" # change this to your name
logo_url:           https://avatars0.githubusercontent.com/u/16758612?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://blueybloke.github.io # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap

# Analytics
#jekyll_analytics:
#  GoogleAnalytics:          # Add, if you want to track with Google Analytics
#    id: UA-129795936-1          # Required - replace with your tracking id
#    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
